import "./index.css";
import { Composition } from "remotion";
import { HelloWorld, myCompSchema } from "./HelloWorld";
import { Logo, myCompSchema2 } from "./HelloWorld/Logo";
import { Main, myVideoSchema } from "./Video/Main";
import { TimelineVideo, timelineVideoSchema } from "./Video/TimelineVideo";
import { parseTimeline } from "../spec/timeline.schema";

// Static import of timeline from src/generated (SSOT)
// This file is generated by: npm run pipeline
// A dummy file exists in the repo to allow static import before pipeline runs
import timelineJson from "./generated/timeline.json";

// Validate timeline with Zod at module load time
const timeline = parseTimeline(timelineJson);

// Each <Composition> is an entry in the sidebar!

export const RemotionRoot: React.FC = () => {
  const fps = timeline.meta.fps;
  const durationInFrames = Math.max(timeline.meta.totalFrames, 60);

  return (
    <>
      {/* Timeline-based composition (primary) */}
      <Composition
        id="TimelineVideo"
        component={TimelineVideo}
        durationInFrames={durationInFrames}
        fps={fps}
        width={timeline.meta.width}
        height={timeline.meta.height}
        schema={timelineVideoSchema}
        defaultProps={{
          titleText: "自動生成動画テスト",
          timeline: timeline,
        }}
      />

      {/* Legacy composition (kept for backward compatibility) */}
      <Composition
        id="MyVideo"
        component={Main}
        durationInFrames={Math.max(durationInFrames, 300)}
        fps={fps}
        width={1920}
        height={1080}
        schema={myVideoSchema}
        defaultProps={{
          titleText: "自動生成動画テスト (Legacy)",
        }}
      />

      <Composition
        id="HelloWorld"
        component={HelloWorld}
        durationInFrames={150}
        fps={30}
        width={1920}
        height={1080}
        schema={myCompSchema}
        defaultProps={{
          titleText: "Welcome to Remotion",
          titleColor: "#000000",
          logoColor1: "#91EAE4",
          logoColor2: "#86A8E7",
        }}
      />

      <Composition
        id="OnlyLogo"
        component={Logo}
        durationInFrames={150}
        fps={30}
        width={1920}
        height={1080}
        schema={myCompSchema2}
        defaultProps={{
          logoColor1: "#91dAE2" as const,
          logoColor2: "#86A8E7" as const,
        }}
      />
    </>
  );
};
