import "./index.css";
import { Composition } from "remotion";
import { HelloWorld, myCompSchema } from "./HelloWorld";
import { Logo, myCompSchema2 } from "./HelloWorld/Logo";
import { Main, myVideoSchema } from "./Video/Main";
import { TimelineVideo, timelineVideoSchema } from "./Video/TimelineVideo";
import audioManifest from "./audio_manifest.json";
import type { Timeline } from "../spec/timeline.schema";

// Import timeline from src/generated (stable path within src)
// This file is generated by: npm run pipeline
let timeline: Timeline | undefined;
try {
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  timeline = require("./generated/timeline.json") as Timeline;
} catch {
  // Timeline not generated yet - this is fine, use legacy mode
  console.log("[Root] Timeline not found in src/generated, using legacy mode");
}

// Each <Composition> is an entry in the sidebar!

export const RemotionRoot: React.FC = () => {
  
  // Calculate total duration based on audio manifest (legacy mode)
  const fps = 30;
  const bufferPerClip = 0.5; // Must match ScenarioPlayer buffer
  const legacyDurationInSeconds = audioManifest.reduce((acc, item) => acc + item.durationInSeconds + bufferPerClip, 0);
  const legacyDurationInFrames = Math.ceil(legacyDurationInSeconds * fps);

  // Timeline-based duration
  const timelineDurationInFrames = timeline?.meta.totalFrames ?? legacyDurationInFrames;

  return (
    <>
      {/* Timeline-based composition (new) */}
      {timeline && (
        <Composition
          id="TimelineVideo"
          component={TimelineVideo}
          durationInFrames={Math.max(timelineDurationInFrames, 300)}
          fps={timeline.meta.fps}
          width={timeline.meta.width}
          height={timeline.meta.height}
          schema={timelineVideoSchema}
          defaultProps={{
            titleText: "自動生成動画テスト",
            timeline: timeline,
          }}
        />
      )}

      {/* Legacy composition (kept for backward compatibility) */}
      <Composition
        id="MyVideo"
        component={Main}
        durationInFrames={Math.max(legacyDurationInFrames, 300)}
        fps={fps}
        width={1920}
        height={1080}
        schema={myVideoSchema}
        defaultProps={{
            titleText: "自動生成動画テスト (Legacy)",
        }}
      />

      <Composition
        id="HelloWorld"
        component={HelloWorld}
        durationInFrames={150}
        fps={30}
        width={1920}
        height={1080}
        schema={myCompSchema}
        defaultProps={{
          titleText: "Welcome to Remotion",
          titleColor: "#000000",
          logoColor1: "#91EAE4",
          logoColor2: "#86A8E7",
        }}
      />

      <Composition
        id="OnlyLogo"
        component={Logo}
        durationInFrames={150}
        fps={30}
        width={1920}
        height={1080}
        schema={myCompSchema2}
        defaultProps={{
          logoColor1: "#91dAE2" as const,
          logoColor2: "#86A8E7" as const,
        }}
      />
    </>
  );
};
